export enum TripEventType {
  TRIP_REQUESTED = 'trip_requested',
  DRIVER_ASSIGNED = 'driver_assigned',
  DRIVER_ACCEPTED = 'driver_accepted',
  DRIVER_ARRIVED_PICKUP = 'driver_arrived_pickup',
  TRIP_STARTED = 'trip_started',
  TRIP_COMPLETED = 'trip_completed',
  TRIP_CANCELED = 'trip_canceled',
  PAYMENT_FAILED = 'payment_failed',
  PAYMENT_CONFIRMED = 'payment_confirmed',
  NO_DRIVERS_FOUND = 'no_drivers_found',
  FARE_RECALCULATED = 'fare_recalculated',
  DRIVER_REJECTED = 'driver_rejected',
  PICKUP_POINT_CHANGED = 'pickup_point_changed',
  DROPOFF_POINT_CHANGED = 'dropoff_point_changed',
  LOCATION_UPDATE = 'location_update',
  DISCOUNT_APPLIED = 'discount_applied',
  PENALTY_APPLIED = 'penalty_applied',
}
